/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bfdepovyxblizwnwrkie"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZGVwb3Z5eGJsaXp3bndya2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwMzg5NDAsImV4cCI6MjA5MzYxNDk0MH0.0DiAv-4a-8lFLp40IlFM8rvDcTUE9c30o2WwtYK5dEA"